SET TITLE
'Parametros de minimizacao de curva sigmagg'
PARAMETERS
1 'A1' 0.9000D0 1.D-5  0.3d0   0.9d0
2 'A2' 1.3730D0 1.D-5  1.D-5   5.d0

set errordef 4.605
SIMPLEX
SIMPLEX
MIGRAD
MIGRAD
MIGRAD
HESSE
RETURN






#fix 1
#MIGRAD
#MIGRAD
#release 1
#MIGRAD
#MIGRAD
#HESSE
#RETURN
