SET TITLE
'Parametros de minimizacao de curva sigmagg'
PARAMETERS
1 'A1' 0.9000D0 1.D-5  0.25d0   1.0d0
2 'A2' 1.3730D0 1.D-3  0.8d0   2.d0

set errordef 4.605
MIGRAD
MIGRAD
MIGRAD
HESSE
RETURN






#fix 1
#MIGRAD
#MIGRAD
#release 1
#MIGRAD
#MIGRAD
#HESSE
#RETURN
